---
- name: Check /root/bin
  files: path=/root/bin state=directory
- name: Copying rvm-installer script
  copy: src=./rvm-installer dest=/root/bin/rvm-installer
- name: Installing RVM   
  command: /root/bin/rvm-installer stable
- name: Seting RVM autolibs on
  command: /usr/local/rvm/bin/rvm autolibs 3

